services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_PATH=/opt/webapp/explainshell.db
      - HOST_IP=0.0.0.0
    volumes:
      - .:/opt/webapp
      - venv:/opt/webapp/.venv
    ports:
      - "5001:5000"

volumes:
  venv:
