version: '2'
services:
  db:
    image: mongo
    container_name: explainshell-db
    restart: always
  web:
    build: .
    command: make serve
    container_name: explainshell
    restart: always
    environment:
      - MONGO_URI=mongodb://db
      - HOST_IP=0.0.0.0
    volumes:
      - .:/opt/webapp
    ports:
      - "5000:5000"
    depends_on:
      - db
