services:
  db:
    image: mongo
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://db
      - HOST_IP=0.0.0.0
    volumes:
      - .:/opt/webapp
    ports:
      - "5000:5000"
    depends_on:
      - db
