version: '2'
services:
  db:
    image: mongo
  web:
    build: .
    command: make serve
    environment:
      - MONGO_URI=mongodb://db
    volumes:
      - .:/opt/webapp
    ports:
      - "5000:5000"
    depends_on:
      - db
