# fly.toml app configuration file generated for explainshell on 2026-03-05T12:24:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'explainshell'
primary_region = 'iad'

[build]

[env]
  DB_PATH = '/data/explainshell.db'
  DB_URL = 'https://github.com/idank/explainshell/releases/download/db-latest/explainshell.db'
  DB_VERSION = '6'
  DEBUG = 'false'
  HOST_IP = '0.0.0.0'
  PORT = '8080'

[[mounts]]
  source = 'explainshell_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "60s"
    method = "get"
    path = "/"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
