# fly.toml app configuration file generated for explainshell on 2026-03-05T12:24:22+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'explainshell'
primary_region = 'iad'

[build]

[deploy]
  strategy = "bluegreen"

[env]
  DB_PATH = '/opt/webapp/explainshell.db'
  DEBUG = 'false'
  HOST_IP = '0.0.0.0'
  PORT = '5000'

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 2

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "60s"
    method = "get"
    path = "/"

[[vm]]
  size = 'shared-cpu-1x'
  memory = '2gb'
  cpus = 1
