#!/bin/bash -e

while read url; do
	if [ -f $(printf "$url" | cut -d / -f 7) ]; then
		continue
	fi

	python -c 'import time, random; time.sleep(float(random.randint(1000, 2000)) / 1000)'
	wget -nv "$url" || echo "$url" >> failed
done < gzlist8

mv -f *.8.gz ../manpages/8/
