# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches:
      - master

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy app
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    concurrency: deploy-group
    environment: production
    steps:
      - uses: actions/checkout@v6
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
